### ISSUE TITLE
Add a link to context menu?

### ISSUE THREAD

**Issue by leocaseiro** [rknightuk/github-pages-chrome#1]
Has being a while that chrome shows extensions since this was created. I was wondering if we could add a feature to go to github source in the context menu, instead? So I could hide the icon of this extension.

I'm happy to raise a PR.

**Comment by rknightuk** [comment]
I don't use this extension any more so I haven't looked into any upgrades or anything. You might be better off forking and making changes to your own version as I doubt I'll have time to upload a new version.
